export const SUCCESS = "SUCCESS";

export const ERROR_WORNG_CHAT_PASSWORD = "ERROR_WORNG_CHAT_PASSWORD";
export const ERROR_EMPTY_CHAT_PASSWORD = "ERROR_EMPTY_CHAT_PASSWORD";
export const ERROR_EMPTY_ROOM_ID = "ERROR_EMPTY_ROOM_ID";
export const ERROR_CHAT_ROOM_SETTING_NOT_EXIST = "ERROR_CHAT_ROOM_SETTING_NOT_EXIST";


